# Generated by Django 4.2.16 on 2024-11-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0003_recipeingredient_unique_recipes_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Укажите вес в граммах', max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=0),
        ),
    ]
