# Generated by Django 4.2.16 on 2024-11-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0004_ingredient_image_ingredient_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Калорийность в ккал на 100 грамм', max_digits=6),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=2, help_text='Количество порций (по умолчанию 2)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Вес в граммах', max_digits=6),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Вес в граммах', max_digits=6),
        ),
    ]
