# Generated by Django 4.2.16 on 2024-11-04 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0006_remove_ingredient_weight_remove_recipe_servings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(default='Описание рецепт', help_text='Описание'),
        ),
    ]
