# Generated by Django 4.2.16 on 2024-11-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0009_ingredient_unit_alter_ingredient_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='conversion_to_grams',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Коэффициент преобразования в граммы (для нестандартных единиц)', max_digits=6, verbose_name='Коэффициент в граммы'),
        ),
    ]
