# Generated by Django 4.2.16 on 2024-11-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0011_remove_ingredient_conversion_to_grams_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='milliliters',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='pieces',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='tablespoons',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='teaspoons',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='weight_in_grams',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='conversion_to_grams',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'Граммы'), ('pcs', 'Штуки'), ('tbsp', 'Столовые ложки'), ('tsp', 'Чайные ложки'), ('ml', 'Миллилитры')], default='g', max_length=10, verbose_name='Единица измерения'),
        ),
    ]
