# Generated by Django 4.2.16 on 2024-12-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0014_remove_ingredient_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='Единица измерения')),
                ('key', models.CharField(max_length=10, unique=True, verbose_name='Сокращение')),
            ],
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='conversion_to_grams',
            new_name='weight_by_pcs',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_catalog.measurementscale', verbose_name='Единица измерения'),
        ),
    ]
