# Generated by Django 4.2.16 on 2024-12-01 13:21

from django.db import migrations, models
import django.db.models.deletion


def add_volumeunitconversion(apps, schema_editor):
    VolumeUnitConversion = apps.get_model('recipe_catalog', 'VolumeUnitConversion')
    MeasurementScale = apps.get_model('recipe_catalog', 'MeasurementScale')

    tsp = MeasurementScale.objects.get(key='tsp')
    tbsp = MeasurementScale.objects.get(key='tbsp')

    VolumeUnitConversion.objects.create(unit=tsp, weight=5)
    VolumeUnitConversion.objects.create(unit=tbsp, weight=15)


class Migration(migrations.Migration):
    dependencies = [
        ('recipe_catalog', '0018_volumeunitconversion'),
    ]

    operations = [
        migrations.RunPython(add_volumeunitconversion),
    ]
