# Generated by Django 4.2.16 on 2024-12-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0019_volumeunitconversion_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='weight',
            field=models.IntegerField(default=0, help_text='Вес в граммах'),
        ),
    ]
