# Generated by Django 4.2.16 on 2024-12-01 13:59

from django.db import migrations, models
import recipe_catalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0021_remove_recipeingredient_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='count',
            field=models.IntegerField(default=0, help_text=recipe_catalog.models.RecipeIngredient.get_help_text),
        ),
    ]
