# Generated by Django 4.2.16 on 2024-12-01 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0022_alter_recipeingredient_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
