# Generated by Django 4.2.16 on 2024-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0023_alter_recipeingredient_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementscale',
            name='abbreviation',
            field=models.TextField(default=''),
        ),
    ]
