# Generated by Django 4.2.16 on 2024-12-02 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0028_remove_ingredient_unit_recipeingredient_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_catalog.measurementscale', verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(default=0, help_text='Калорийность на 100 ед. изм.', verbose_name='Калорийность'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe_catalog.recipe'),
        ),
    ]
