# Generated by Django 4.2.16 on 2024-12-03 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0031_alter_recipeingredient_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='unit',
        ),
    ]
