# Generated by Django 4.2.16 on 2024-12-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0037_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='total_calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая калорийность (ккал)'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_weight',
            field=models.IntegerField(default=0, verbose_name='Общий вес (грамм)'),
        ),
    ]
