# Generated by Django 4.2.16 on 2024-12-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0040_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementscale',
            name='key',
            field=models.CharField(max_length=10, verbose_name='Сокращение'),
        ),
    ]
