# Generated by Django 4.2.16 on 2024-12-06 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0044_alter_volumeunitconversion_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volumeunitconversion',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe_catalog.measurementscale'),
        ),
    ]
