# Generated by Django 4.2.16 on 2024-12-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0045_alter_volumeunitconversion_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название'),
        ),
    ]
