# Generated by Django 4.2.16 on 2024-12-06 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0048_alter_ingredient_name_alter_measurementscale_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(default=0, help_text='Калорийность на 100 ед. изм.', validators=[django.core.validators.MinValueValidator(0.1, 'Conversion rate must be positive.')], verbose_name='Калорийность'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.TextField(default='Ингредиент', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Name should be a string value.', regex='^[A-Za-zА-Яа-яёЁ\\s]+$')], verbose_name='Название'),
        ),
    ]
