# Generated by Django 4.2.16 on 2024-12-06 10:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_catalog', '0049_alter_ingredient_calories_alter_ingredient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(default=0, help_text='Калорийность на 100 ед. изм.', validators=[django.core.validators.MinValueValidator(1, 'Conversion rate must be positive.')], verbose_name='Калорийность'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=0, help_text='Время приготовления в минутах', validators=[django.core.validators.MinValueValidator(1, 'Conversion rate must be positive.')], verbose_name='Время приготовления'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.TextField(max_length=300, unique=True, verbose_name='Название блюда'),
        ),
    ]
