ErrNotString = ValueError("Значение должно быть строкой")
ErrNotEmpty = ValueError("Значение не должно быть пустым")
ErrNotNumber = ValueError("Значение должно быть числом")
ErrNotPositive = ValueError("Значение должно быть положительным")
ErrNotList = ValueError("Ингридиенты должны быть переданы в виде списка")
ErrNotIngredient = ValueError("Передан неверный список ингредиентов")
