version: '3.8'

services:
  django:
    build: ./recipe_project/
    volumes:
      - sqlite_data:/data
      - static:/static
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx/
    volumes:
      - static:/static
    ports:
     - "80:80"

volumes:
  sqlite_data:
  static:
  media: