run:
	cd recipe_project && python manage.py runserver

makemigrations:
	cd recipe_project && python manage.py makemigrations

migrate:
	cd recipe_project && python manage.py migrate

test:
	cd recipe_project && python manage.py test

test-report:
	cd recipe_project && coverage run manage.py test

report:
	cd recipe_project && coverage report

report-html:
	cd recipe_project && coverage html
