run:
	cd recipe_project && python manage.py runserver

makemigrations:
	cd recipe_project && python manage.py makemigrations

migrate:
	cd recipe_project && python manage.py migrate

test:
	cd recipe_project && python manage.py test